//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webapplikasjoner_Del_1_2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBKunde
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DBKunde()
        {
            this.DBOrdres = new HashSet<DBOrdre>();
        }
    
        public int ID { get; set; }
        public string Fornavn { get; set; }
        public string Etternavn { get; set; }
        public System.DateTime Fodselsdag { get; set; }
        public string Adresse { get; set; }
        public int Mobilnummer { get; set; }
        public string Epost { get; set; }
        public byte[] Passord { get; set; }
        public byte[] Salt { get; set; }
        public Nullable<int> Poststed_Postnr { get; set; }
    
        public virtual DBPoststed DBPoststed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DBOrdre> DBOrdres { get; set; }
    }
}
