//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webapplikasjoner_Del_1_2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBOrdrelinje
    {
        public int Id { get; set; }
        public Nullable<int> Film_ID { get; set; }
        public Nullable<int> Ordre_ID { get; set; }
    
        public virtual DBFilm DBFilm { get; set; }
        public virtual DBOrdre DBOrdre { get; set; }
    }
}
