//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webapplikasjoner_Del_1_2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBPoststed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DBPoststed()
        {
            this.DBKundes = new HashSet<DBKunde>();
        }
    
        public int Postnr { get; set; }
        public string Poststed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DBKunde> DBKundes { get; set; }
    }
}
